# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# We will use Ubuntu 18.04 (bionic beaver). List of options:
# https://docs.travis-ci.com/user/reference/overview/#linux
dist: trusty

# This enables the 'defaults' to test java applications:
language: java

services:
  - postgresql

before_script:
  - psql -c 'create database controle;' -U ${SPRING_DATASOURCE_USERNAME}
# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
# jdk:
#  - openjdk8
#  - openjdk11

# Each job in Travis CI has several steps:
# https://docs.travis-ci.com/user/job-lifecycle/
# The 'language: java' directive sets up sane defaults to test common java applications
# We use the defaults for installing dependencies, compiling and testing maven applications
# In our case it will be 'mvn install' followed by 'mvn test'

# This is to enable CodeCov's coverage
# If a build is successful, the code is submitted for coverage analysis
# after_success:
  # - bash <(curl -s https://codecov.io/bash)
  
addons:
  sonarcloud:
      organization: "emegson"
      token:
        secure: "YLHlye6hr8IILdV1mTNfF2amkJq4Hawj64HzI+yJJGRndX3sqIFAIY7yxnITB1kQuMeIw1Gc/7I/tcADuQik6j5Qx9+9IrykClnCYrJBOEKHxMb8/3eMHrMI520V4UXcX2r+UGY2Yd6kZcYKvTa7gya7iVQ2zRVXk/GJx6+gzVMivEYacwmFDJ6sq+lUZSi2sHwVskj/saXB+/rA7Gy6VVakQJXGa1RB5o2dxV6HOkMHGEZtPJc1Uw1M2vXypaXg4sdFr2hdusdIrouQ76U9FxQmlcDiE4dbT+GVIDM7hhMHGnm61CkKrIqqY95BQexpBMryCxdb76AuWzOX1vdkhbJvUDDJYO3RCsQwaVZavvOZ1sbVj8sDmFcwKEIKwyMCm/ry++TO4/VvdUdn+y1XKKSKKLgOSDFxm1nP60J2yFNdx6SJGarFMscE4fVuWvs1WrEQg5EHr9VlNj+6X9n4p3SYdY9/27ARHCm9L+K2lpXIN6UpqGpeFcQSKAqv6yGK1GyriNi4b1KNTCTGe3uaT13doULICzSxPWXTeR3DD1cavgbrw1Kqj6UmxiUqYxKYHP27cm3jVHogoPODsR1kJQQzjgs0E14valwBgtfmXNNgSh4KaLvZ6iCJo3TBM4jkWuy9RDUfabAAzSwfOpM5Sc0X+h+LU2hbZT0SBieZy9s="
        
jobs:
  include:
    # - stage: unit tests
      # script: mvn clean
    - stage: unit tests
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=emegson_financasapi
    # - stage: deploy to staging
      # script: skip
      # deploy: &heroku
        # provider: heroku
        # app: sf-stages-staging
        # api_key: $HEROKU_AUTH_TOKEN
    # - stage: test staging
      # script: 'curl https://filhoemer-staging.herokuapp.com'
    # - stage: deploy to production
      # script: skip
      # deploy:
        # <<: *heroku
        # app: sf-stages-production
    # - stage: test production
      # script: 'curl https://filhoemer-production.herokuapp.com/'
