dist: trusty
language: java
services:
- postgresql
cache:
- directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_script:
- psql -c 'create database controle;' -U $SPRING_DATASOURCE_USERNAME
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: emegson
    token:
      secure: YLHlye6hr8IILdV1mTNfF2amkJq4Hawj64HzI+yJJGRndX3sqIFAIY7yxnITB1kQuMeIw1Gc/7I/tcADuQik6j5Qx9+9IrykClnCYrJBOEKHxMb8/3eMHrMI520V4UXcX2r+UGY2Yd6kZcYKvTa7gya7iVQ2zRVXk/GJx6+gzVMivEYacwmFDJ6sq+lUZSi2sHwVskj/saXB+/rA7Gy6VVakQJXGa1RB5o2dxV6HOkMHGEZtPJc1Uw1M2vXypaXg4sdFr2hdusdIrouQ76U9FxQmlcDiE4dbT+GVIDM7hhMHGnm61CkKrIqqY95BQexpBMryCxdb76AuWzOX1vdkhbJvUDDJYO3RCsQwaVZavvOZ1sbVj8sDmFcwKEIKwyMCm/ry++TO4/VvdUdn+y1XKKSKKLgOSDFxm1nP60J2yFNdx6SJGarFMscE4fVuWvs1WrEQg5EHr9VlNj+6X9n4p3SYdY9/27ARHCm9L+K2lpXIN6UpqGpeFcQSKAqv6yGK1GyriNi4b1KNTCTGe3uaT13doULICzSxPWXTeR3DD1cavgbrw1Kqj6UmxiUqYxKYHP27cm3jVHogoPODsR1kJQQzjgs0E14valwBgtfmXNNgSh4KaLvZ6iCJo3TBM4jkWuy9RDUfabAAzSwfOpM5Sc0X+h+LU2hbZT0SBieZy9s=
jobs:
  include:
  - stage: unit tests
    script: mvn clean verify sonar:sonar -Dsonar.projectKey=emegson_financasapi -Pcoverage
  - stage: test production
    script: curl https://filhoemer.herokuapp.com/healthCheck