version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME:-postgres}
      POSTGRES_DB: controle
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
#  api:
#    container_name: financasbackend_container
#    build: .
#    volumes:
#      - ./spring:/home/spring/
#    environment:
#      SPRING_PROFILE: ${SPRING_PROFILE:-dev}
#      FIREBASE_URL: ${FIREBASE_URL:-https://financas-98f0c.firebaseio.com/}
#      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
#      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS:-""}
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://postgres:5432/controle}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-postgres}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-postgres}
#    ports:
#      - "8080:8080"
#    networks:
#      - postgres
#    restart: unless-stopped

networks:
  postgres:
    driver: bridge